services:
###> doctrine/doctrine-bundle ###
  db:  # Changé de "database" à "db" pour correspondre à votre config
    ports:
      - "5432"  # Gardez ce port si vous voulez exposer PostgreSQL
      # Ou changez pour MySQL/MariaDB :
      # - "3306"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
