# config/services.yaml
parameters:

services:
    # configuration par défaut
    _defaults:
        autowire: true
        autoconfigure: true


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # add more service definitions when explicit configuration is needed
